### ISSUE TITLE
`config create` plain exits mesosctl

### ISSUE THREAD

**Issue by maltekrupa** [mesoshq/mesosctl#3]
Hi,

if I run `config create` the application just plain exits with an exit code of 0. I couldn't figure out why, so I thought I better create an issue. ;)

Regards
Malte

**Comment by tobilg** [comment]
Hmm... :-/ Sorry! Will have a Look at it later. Does it word if you manually create a config file in the .mesosctl folder and use config load?

**Comment by maltekrupa** [comment]
Yes it does ... take your time.
I just noticed it and thought I share the information.

**Comment by tobilg** [comment]
Thanks. I just fixed it, it was a mistake during refactoring. Automatically testing command-line applications is quite hard unfortunately :-/ 

I published version `0.1.4` on NPM, and the Docker image is currently building. Please have a look if you have time. I guess the build on Docker Hub will take around 2h, it's quite slow today.

**Comment by maltekrupa** [comment]
Works! Thanks a lot!
