### ISSUE TITLE
SSL certificate isn't in the right place for `docker pull`

### ISSUE THREAD

**Issue by maltekrupa** [mesoshq/mesosctl#4]
Hi,

me again. :)

`cluster privision` fails at some point with the following error:

```
Starting task setup
Starting task mesos-dns : Pull Mesos DNS image
-----------------------------------------------------------
Error(s) occurred:
-----------------------------------------------------------
fatal: [host-158221]: FAILED! => {"changed": false, "failed": true, "rc": 1, "stderr": "", "stdout": "Error response from daemon: Get https://registry:5000/v1/_ping: x509: certificate signed by unknown authority\r\n", "stdout_lines": ["Error response from daemon: Get https://registry:5000/v1/_ping: x509: certificate signed by unknown authority"]}
```

The certificate gets generated on the registry node but is
1. not available to the local docker client on the registry node (`/tmp/pull_and_push.sh` fails because of the missing certificate)
2. not available on all other nodes (I'm not sure if it is needed on master and agent nodes or only master nodes ...)

Maybe creating the private key + certificate locally is a better idea, because it might be easier to distribute them to all the nodes. Currently I've done it manually but doing it w/ ansible is obviously the way to go. 

Manual steps:
copy `registry:/opt/registry/certs/registry.crt` to:
`registry:/etc/docker/certs.d/registry:5000/ca.crt`
`master-nodes:/etc/docker/certs.d/registry:5000/ca.crt`

BTW: It looks like you've put a hell lot of work into this project! Amazing!

Regards

**Comment by tobilg** [comment]
Thanks a lot! Could you please specify which OS you're using? The project is tested against three different Vagrant Cluster setups (Ubuntu 14.04, CentOS 7 and CoreOS stable), and it seems to work for me. 

It would be useful to know some setup details of your nodes for further debugging.

**Comment by maltekrupa** [comment]
Currently I'm using 2gb digitalocean VMs. One for the registry, three master and three agent nodes.

I'm not sure what caused the problem yesterday ... maybe it was just too late. Works like a charm now. Thanks a lot for the quick help!

**Comment by tobilg** [comment]
Ah, ok :-) Thanks for the feedback. 2GB VMs seem rather small to me though... I tend to use some [Scaleway x64 instances](https://www.scaleway.com/pricing/). They have more RAM and more cores... They're a little tricky to setup unfortunately.

Also, you could theoretically just use 3 instances, and run the Masters and Agents on the same instance, and the registry on one of the three instances. 

This is not really recommended for production, but works like a charm for me for testing and framework development.

Glad you got everything to work! Thanks again for your feedback!
